-- Clausula WHERE acompanhada de AND, OR e NOT
-- Os operadores AND e OR são usados ​​para filtrar registros com base em mais de uma condição:
    -- O AND operador exibe um registro se todas as condições separadas por AND for em TRUE.
    -- O OR operador exibe um registro se alguma das condições separadas por OR for TRUE.
-- O NOT operador exibe um registro se a(s) condição(ões) NÃO for VERDADEIRA.